version: "3.9"

services:

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: utxsathish-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sathish@123
      POSTGRES_DB: mydatabase
    ports:
      - "9001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    restart: unless-stopped

  pgagent:
    build:
      context: .
      dockerfile: Dockerfile.pgagent
    container_name: utxsathish-pgagent
    depends_on:
      - postgres
    networks:
      - postgres_network
    restart: unless-stopped
    command: >
      bash -c "
      until pg_isready -h postgres -U postgres; do sleep 2; done &&
      pgagent -f host=postgres dbname=mydatabase user=postgres password=Sathish@123
      "

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
