version: "3.9"

services:

  postgres:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: appdb
    command: postgres -c work_mem=16MB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  pgagent:
    image: postgres:18
    container_name: pgagent
    depends_on:
      - postgres
    environment:
      PGPASSWORD: admin
    entrypoint: >
      bash -c "
      apt-get update &&
      apt-get install -y pgagent &&
      sleep 10 &&
      pgagent host=postgres dbname=appdb user=admin password=admin
      "

volumes:
  pgdata:
