services:

  postgres:
    image: postgres:17
    container_name: utxsathish-postgres
    hostname: utxsathish
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sathish@123
      POSTGRES_DB: mydatabase
    ports:
      - "9001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y pgagent &&
      postgres -c work_mem=16MB &
      sleep 10 &&
      pgagent host=localhost dbname=mydatabase user=postgres &
      wait
      "

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
