services:

  postgres:
    image: postgres:17
    container_name: utxsathish-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sathish@123
      POSTGRES_DB: mydatabase
    ports:
      - "9001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    command: postgres -c work_mem=16MB

  pgagent:
    image: dpage/pgadmin4:latest
    container_name: utxsathish-pgagent
    depends_on:
      - postgres
    networks:
      - postgres_network
    entrypoint: >
      /bin/sh -c "
      apt update &&
      apt install -y pgagent &&
      pgagent host=postgres dbname=mydatabase user=postgres password=Sathish@123
      "

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
