services:

  postgres:
    image: postgres:17
    container_name: utxsathish-postgres
    hostname: utxsathish
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sathish@123
      POSTGRES_DB: mydatabase
    command: postgres -c work_mem=16MB
    ports:
      - "9001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  pgagent:
    image: postgres:17
    container_name: utxsathish-pgagent
    depends_on:
      - postgres
    environment:
      PGPASSWORD: Sathish@123
    entrypoint: >
      bash -c "
      apt-get update &&
      apt-get install -y pgagent &&
      sleep 10 &&
      pgagent host=postgres dbname=mydatabase user=postgres password=Sathish@123
      "
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
